# require: rubocop-jekyll
# inherit_gem:
#  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
      - vendor/**/*
      - Gemfile*
      - '*.gemspec' # This does nothing. Why?
  NewCops: enable
  TargetRubyVersion: 2.6

# Gemspec/RequireMFA:
#   Enabled: false

# Jekyll/NoPutsAllowed:
#   Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false
