require: rubocop-jekyll
inherit_gem:
 rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
      - vendor/**/*
      - Gemfile*
      - '*.gemspec' # This does nothing. Why?
  NewCops: enable
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 150

# Gemspec/RequireMFA:
#   Enabled: false

Jekyll/NoPutsAllowed:
  Enabled: false
