#!/bin/bash

# shellcheck disable=SC2086

run="jekyll serve \
    --livereload_port 35721 \
    --force_polling \
    --host 0.0.0.0 \
    --port 4444 \
    --future \
    --incremental \
    --livereload \
    --drafts \
    --unpublished"

function debug {
  bundle exec rdebug-ide \
    --host 0.0.0.0 \
    --port 1234 \
    --dispatcher-port 26162 \
    -- $run
}

GIT_ROOT="$( git rev-parse --show-toplevel )"
cd "${GIT_ROOT}/demo" || exit

bundle install
if [ "$1" == -r ]; then
  bundle exec $run
else
  debug
fi
