source 'https://rubygems.org'

gem 'confidential_info_redactor'
gem 'ffi'
gem 'jekyll', '~> 4.3.2'
gem 'nokogumbo', '=2.0.3'
gem 'ptools'
gem 'talk_like_a_pirate', ">= 0.2.2"

group :jekyll_plugins do
  gem 'classifier-reborn'
  gem 'html-proofer'
  gem 'jekyll-assets'
  gem 'jekyll-environment-variables'
  gem "jekyll_plugin_logger"
  gem 'jekyll_plugin_template', path: '../'
  gem 'jekyll-sort'
  gem 'jekyll-tagging'
  gem 'kramdown'
end

gem 'debase', '0.2.5.beta2', require: false
gem "rake", require: false
gem 'rspec', require: false
gem 'rubocop', require: false
gem 'ruby-debug-ide', require: false
